name: Python - docker build and push images to dockerhub

on:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  DOCKER_BUILDKIT: '1'
  # TARGET_PLATFORMS: "linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x"
  TARGET_PLATFORMS: "linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x"
  PUSH: true


jobs:
  python:
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11-rc"]
        slim: ["-slim", ""]
    continue-on-error: true
    runs-on: ubuntu-22.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
          config-inline: |
                      [worker.oci]
                        max-parallelism = 1
      - name: Build python-cryptography using python${{ matrix.python-version }}${{ matrix.slim }}
        uses: docker/build-push-action@v3
        with:
          file: python/python-cryptography.dockerfile
          platforms: ${{ env.TARGET_PLATFORMS }}
          push: false
          target: export-wheels
          tags: |
            python${{ matrix.python-version }}${{ matrix.slim }}-cryptography
          build-args: PYVER=${{ matrix.python-version }}${{ matrix.slim }}
          outputs: type=local,dest=/tmp/cryptography-wheels
          ulimit: nofile=262144:262144
          # outputs: type=docker,dest=/tmp/python${{ matrix.python-version }}${{ matrix.slim }}-cryptography.tar
      - name: List wheels directory
        run: |
          ls -R /tmp/cryptography-wheels
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.python-version }}${{ matrix.slim }}-cryptography
          path: /tmp/cryptography-wheels
