name: cross using rust base image

on:
  push:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  DOCKER_BUILDKIT: '1'
#  TARGET_PLATFORMS: "linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x"
#  PUSH: true


jobs:
  python:
    strategy:
      max-parallel: 1
      matrix:
#        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11-rc"]
#        platform: ["linux/amd64", "linux/arm/v7", "linux/arm64/v8", "linux/ppc64le", "linux/s390x"]
        python-version: ["3.10"]
        platform: ["linux/arm/v7"]
    continue-on-error: true
    runs-on: ubuntu-22.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Create buildkitd config override
        run: |
          echo "[worker.oci]" > /tmp/buildkitd.toml
          echo "  max-parallelism = 1" >> /tmp/buildkitd.toml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
          config: /tmp/buildkitd.toml
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build cross wheels for ${{ matrix.platform }} using rust-python${{ matrix.python-version }}
        uses: docker/build-push-action@v3
        with:
          file: python/rust-python-cross.dockerfile
#          platforms: ${{ env.TARGET_PLATFORMS }}
          platforms: ${{ matrix.platform }}
          push: false
          target: export-wheels
          tags: |
            rust-python${{ matrix.python-version }}-cross_${{ matrix.platform }}
          build-args: PYVER=${{ matrix.python-version }},PACKAGES="pycparser cffi greenlet lxml MarkupSafe msgpack SQLAlchemy tornado wrapt cryptography PyNaCl"
          outputs: type=local,dest=/tmp/cross-wheels
          ulimit: nofile=262144:262144
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          # outputs: type=docker,dest=/tmp/python${{ matrix.python-version }}-cross.tar
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache to prevent docker cache leak
        if: always()
        run: |
          if [ -e /tmp/.buildx-cache-new ]; then rm -rf /tmp/.buildx-cache && mv /tmp/.buildx-cache-new /tmp/.buildx-cache fi
      - name: List wheels directory
        run: |
          ls -R /tmp/cross-wheels
      - name: Upload linux/amd64 wheels
        uses: actions/upload-artifact@v3
        with:
          name: amd64
          path: /tmp/cross-wheels/linux_amd64
      - name: Upload linux/arm64 wheels
        uses: actions/upload-artifact@v3
        with:
          name: arm64
          path: /tmp/cross-wheels/linux_arm64
      - name: Upload linux/arm/v7 wheels
        uses: actions/upload-artifact@v3
        with:
          name: armv7
          path: /tmp/cross-wheels/linux_arm_v7
      - name: Upload linux/ppc64le wheels
        uses: actions/upload-artifact@v3
        with:
          name: ppc64le
          path: /tmp/cross-wheels/linux_ppc64le
      - name: Upload linux/s390x wheels
        uses: actions/upload-artifact@v3
        with:
          name: s390x
          path: /tmp/cross-wheels/linux_s390x
